version: "3.9"

networks:
  db:

volumes:
  pgdata:


services:
  forcecodes_api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000" ]
    depends_on: [ db ]
    networks:
      - db
    environment:
      DB_CONN_STRING: "postgresql+asyncpg://test:test@db:5432/test"

  db:
    image: postgres:alpine
    restart: unless-stopped
    user: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db

  dbpgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on: [ db ]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    ports:
      - "5050:80"
    networks:
      - db